### ISSUE TITLE
Still cant get Images on Ubuntu

### ISSUE THREAD

**Issue by dopf-26** [camenduru/stable-diffusion-webui-artists-to-study#3]
Sorry, should have update my initial post with the error output. Seems like there are still \\ present.

Console output:
```
Traceback (most recent call last):
  File "/home/liam/Documents/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/routes.py", line 275, in run_predict
    output = await app.blocks.process_api(
  File "/home/liam/Documents/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 791, in process_api
    predictions = self.postprocess_data(fn_index, result["prediction"], state)
  File "/home/liam/Documents/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/blocks.py", line 759, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/home/liam/Documents/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/components.py", line 3291, in postprocess
    file = processing_utils.create_tmp_copy_of_file(
  File "/home/liam/Documents/stable-diffusion-webui/venv/lib/python3.10/site-packages/gradio/processing_utils.py", line 341, in create_tmp_copy_of_file
    shutil.copy2(file_path, file_obj.name)
  File "/usr/lib/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:

FileNotFoundError: [Errno 2] No such file or directory: '/home/liam/Documents/stable-diffusion-webui/extensions/stable-diffusion-webui-artists-to-study/ats/thumbnail/dog/anime\\anime_Adam Hughes_0.60854626_1470.jpg'
```

**Comment by camenduru** [comment]
@Chilluminati91 thanks I hope this time works 🤞

**Comment by dopf-26** [comment]
Works fine now, thanks!
